# Clue - An alternative package manager for Nim development
#
# (c) 2026 George Lemon | MIT License
#          Made by Humans from OpenPeeps
#          https://github.com/openpeeps/clue

## `clue deploy.init` — scaffold `clue.deploy.yaml` (and optionally
## `.github/workflows/release.yml`) for the current nimble project.

import std/[os, osproc, strutils, terminal]
import pkg/kapsis/interactive/prompts
import ../pkgmanager/configs
import ../pkgmanager/nimbleparser

proc parseGitRepo*(url: string): string =
  ## Normalize a git remote URL to `owner/repo`.
  var u = url.strip()
  if u.len == 0:
    return ""
  if u.endsWith(".git"):
    u = u[0 ..< u.len - 4]
  let atIdx = u.rfind('@')
  if atIdx >= 0:
    u = u[atIdx + 1 .. ^1]
  if u.startsWith("git+"):
    u = u[4 .. ^1]
  let scheme = u.find("://")
  if scheme >= 0:
    u = u[scheme + 3 .. ^1]
  let colonIdx = u.find(':')
  if colonIdx >= 0:
    u = u[colonIdx + 1 .. ^1]
  else:
    let slashIdx = u.find('/')
    if slashIdx >= 0:
      u = u[slashIdx + 1 .. ^1]
    else:
      u = ""
  u

proc gitOriginRepo*(): string =
  ## The current repository's GitHub `owner/repo` ("" if none).
  let (outp, code) = execCmdEx("git config --get remote.origin.url")
  if code != 0:
    return ""
  parseGitRepo(outp)

proc detectNimVersion*(): string =
  ## The installed `nim --version` as `major.minor.patch` (fallback 2.2.10).
  let (outp, code) = execCmdEx("nim --version")
  if code != 0:
    return "2.2.10"
  for line in outp.splitLines():
    if "Nim Compiler Version" in line:
      for w in line.splitWhitespace():
        if w.len > 0 and w[0] in {'0'..'9'}:
          let parts = w.split('.')
          if parts.len >= 2:
            return if parts.len >= 3: parts[0] & "." & parts[1] & "." & parts[2]
                   else: parts[0] & "." & parts[1]
  "2.2.10"

proc buildDeployYaml(project, deployType, version, repo, host, user, remoteDir: string): string =
  result = """# clue.deploy.yaml - generated by clue deploy.init
project: @@PROJECT@@
type: @@TYPE@@
version: "@@VERSION@@"
github:
  repo: @@REPO@@

release:
  repo: @@REPO@@
  tagPrefix: ""
  notes: ""
  draft: false
  prerelease: false
  assets: []
  workflow: .github/workflows/release.yml
  targets:
    - {os: ubuntu-latest, arch: x86_64}
    - {os: macos-14, arch: arm64}
    - {os: macos-15-intel, arch: x86_64}
    - {os: windows-latest, arch: x86_64}
  artifactName: "{{project}}_{{os}}-{{arch}}"

web:
  localDir: dist/web
  profiles:
    production:
      host: "@@HOST@@"
      user: "@@USER@@"
      remoteDir: "@@REMOTEDIR@@"
      port: 22
      sshKey: ~/.ssh/id_ed25519
      exclude: [".DS_Store", "*.tmp"]
      delete: false
      checksum: false
      compress: true
      partial: true
      timeout: 60
      preBuild: []
      postDeploy: []
      systemd:
        service: "@@SERVICE@@"
        daemonReload: true
        enable: true
        restart: true
        sudo: true
        status: true
"""
  result = result
    .replace("@@PROJECT@@", project)
    .replace("@@TYPE@@", deployType)
    .replace("@@VERSION@@", version)
    .replace("@@REPO@@", repo)
    .replace("@@HOST@@", host)
    .replace("@@USER@@", user)
    .replace("@@REMOTEDIR@@", remoteDir)
    .replace("@@SERVICE@@", project)

proc buildReleaseWorkflow(appName, nimVersion: string): string =
  result = """name: release
on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:
env:
  APP_NAME: '@@APP_NAME@@'
  NIM_VERSION: '@@NIM_VERSION@@'

jobs:
  build-artifact:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: macos-14
            arch: arm64
          - os: macos-15-intel
            arch: x86_64
          - os: windows-latest
            arch: x86_64
    steps:
      - uses: actions/checkout@v4

      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v4
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-${{ runner.arch }}-nim-${{ env.NIM_VERSION }}-nimble-${{ hashFiles('**/*.nimble', '**/nimble.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-nim-${{ env.NIM_VERSION }}-nimble-
            ${{ runner.os }}-${{ runner.arch }}-nimble-
        if: runner.os != 'Windows'

      - uses: georgelemon/setup-nim-action@master
        with:
          nim-version: ${{ env.NIM_VERSION }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - run: nimble install -y --depsOnly
      - run: nimble build -y

      - name: Create artifact
        shell: bash
        run: |
          os="${{ runner.os }}"
          arch="${{ matrix.arch }}"
          suffix="$os${arch:+-$arch}"
          assets="${{ env.APP_NAME }}_$(echo "$suffix" | tr '[:upper:]' '[:lower:]')"
          mkdir -p "dist/$assets"
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            cp bin/${{ env.APP_NAME }}.exe LICENSE README.md "dist/$assets/"
            (cd dist && 7z a "$assets.zip" "$assets")
          else
            cp bin/${{ env.APP_NAME }} LICENSE README.md "dist/$assets/"
            (cd dist && tar czf "$assets.tar.gz" "$assets")
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.os }}-${{ matrix.arch }}
          path: dist/*

  release:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    permissions:
      contents: write
    needs:
      - build-artifact
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          pattern: artifact-*
          path: dist
          merge-multiple: true

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ github.ref_name }}" \
            --title "${{ github.ref_name }}" \
            --notes "Release" \
            --draft=false \
            --prerelease=false \
            dist/*.tar.gz dist/*.zip
"""
  result = result.replace("@@APP_NAME@@", appName).replace("@@NIM_VERSION@@", nimVersion)

proc initDeploy*(deployType: string, writeWorkflow, yes, force: bool) =
  ## Scaffold `clue.deploy.yaml` (+ optionally `.github/workflows/release.yml`).
  let projectFs = newProjectDisk()
  let nimblePath = findNimbleFile(getCurrentDir(), getClueCfg(), projectFs)
  if nimblePath.len == 0:
    displayError("No .nimble file found in " & getCurrentDir() & ". `clue deploy.init` needs a nimble package.", quitProcess = true)
    return
  let nimble = parseNimbleFile(nimblePath)
  let project = nimblePath.extractFilename.changeFileExt("")
  let version = if nimble.version.len > 0: nimble.version else: "0.0.0"
  if deployType notin ["cli", "desktop", "web"]:
    displayError("Invalid --type: " & deployType & " (use cli, desktop or web)", quitProcess = true)
    return
  let repo = gitOriginRepo()

  var host = ""
  var user = ""
  var remoteDir = ""
  if deployType == "web":
    host = prompt("Host", default = "").strip()
    user = prompt("User", default = "").strip()
    remoteDir = prompt("Remote dir", default = "").strip()

  let cfgPath = getCurrentDir() / "clue.deploy.yaml"
  if fileExists(cfgPath) and not force:
    displayError("clue.deploy.yaml already exists. Use --force to overwrite.", quitProcess = true)
    return
  writeFile(cfgPath, buildDeployYaml(project, deployType, version, repo, host, user, remoteDir))
  displaySuccess("Created " & cfgPath)

  var genWorkflow = writeWorkflow
  if not genWorkflow and not yes and isatty(stdout):
    genWorkflow = promptConfirm("Generate .github/workflows/release.yml?")
  if genWorkflow:
    let wfPath = getCurrentDir() / ".github" / "workflows" / "release.yml"
    if fileExists(wfPath) and not force:
      displayError(wfPath & " already exists. Use --force to overwrite.", quitProcess = true)
      return
    createDir(wfPath.parentDir())
    writeFile(wfPath, buildReleaseWorkflow(project, detectNimVersion()))
    displaySuccess("Created " & wfPath)
