# Clue - An alternative package manager for Nim development
#
# (c) 2026 George Lemon | MIT License
#          Made by Humans from OpenPeeps
#          https://github.com/openpeeps/clue

## `clue deploy.init` — scaffold `clue.deploy.yaml`
## for the current nimble project.

import std/[os, strutils]
import pkg/kapsis/interactive/prompts
import ../pkgmanager/configs
import ../pkgmanager/nimbleparser

proc buildDeployYaml*(project, deployType, version, host, user, remoteDir: string): string =
  ## Render `clue.deploy.yaml` for `deployType` (`bin` or `static`).
  ## `bin` ships a binary app: a `web` profile with systemd service
  ## management plus `dir` profiles for the binary and any additional
  ## dirs. `static` ships a static dir (e.g. a static website): a `dir`
  ## profile plus a `web` profile without systemd management.
  let header = """# clue.deploy.yaml - generated by clue deploy.init
project: @@PROJECT@@
type: @@TYPE@@
version: "@@VERSION@@"

"""
  let webProfile = """web:
  localDir: @@LOCALDIR@@
  profiles:
    production:
      host: "@@HOST@@"
      user: "@@USER@@"
      remoteDir: "@@REMOTEDIR@@"
      port: 22
      sshKey: ~/.ssh/id_ed25519
      exclude: [".DS_Store", "*.tmp"]
      delete: false
      checksum: false
      compress: true
      partial: true
      timeout: 60
      preBuild: []
      postDeploy: []
@@SYSTEMD@@"""
  let systemdBlock = """      systemd:
        service: "@@SERVICE@@"
        daemonReload: true
        enable: true
        restart: true
        sudo: true
        status: true

"""
  let binDir = """dir:
  profiles:
    binary:
      from: "bin"
      to: "@@REMOTEDIR@@"
      host: "@@HOST@@"
      user: "@@USER@@"
      exclude: ["*.tmp"]
      delete: false
      checksum: false
    # Additional dirs shipped alongside the binary (uncomment as needed):
    # assets:
    #   from: "assets"
    #   to: "@@ASSETSTO@@"
    #   host: "@@HOST@@"
    #   user: "@@USER@@"
    #   exclude: ["*.tmp"]
    #   delete: false
    #   checksum: false
"""
  let staticDir = """dir:
  profiles:
    production:
      from: "dist/site"
      to: "@@REMOTEDIR@@"
      host: "@@HOST@@"
      user: "@@USER@@"
      exclude: ["*.tmp"]
      delete: false
      checksum: false
"""
  if deployType == "static":
    result = header & webProfile.replace("@@SYSTEMD@@", "") & "\n" & staticDir
    result = result.replace("@@LOCALDIR@@", "dist/site")
  else:
    result = header & webProfile.replace("@@SYSTEMD@@", systemdBlock) & binDir
    result = result.replace("@@LOCALDIR@@", "dist/web")
    let assetsTo = if remoteDir.len > 0: remoteDir & "/assets" else: ""
    result = result.replace("@@ASSETSTO@@", assetsTo)
  result = result
    .replace("@@PROJECT@@", project)
    .replace("@@TYPE@@", deployType)
    .replace("@@VERSION@@", version)
    .replace("@@HOST@@", host)
    .replace("@@USER@@", user)
    .replace("@@REMOTEDIR@@", remoteDir)
    .replace("@@SERVICE@@", project)

proc initDeploy*(deployType: string, yes, force: bool) =
  ## Scaffold `clue.deploy.yaml` for the current nimble project.
  let projectFs = newProjectDisk()
  let nimblePath = findNimbleFile(getCurrentDir(), getClueCfg(), projectFs)
  if nimblePath.len == 0:
    displayError("No .nimble file found in " & getCurrentDir() & ". `clue deploy.init` needs a nimble package.", quitProcess = true)
    return
  let nimble = parseNimbleFile(nimblePath)
  let project = nimblePath.extractFilename.changeFileExt("")
  let version = if nimble.version.len > 0: nimble.version else: "0.0.0"

  var host = ""
  var user = ""
  var remoteDir = ""
  host = prompt("Host", default = "").strip()
  user = prompt("User", default = "").strip()
  remoteDir = prompt("Remote dir", default = "").strip()

  let cfgPath = getCurrentDir() / "clue.deploy.yaml"
  if fileExists(cfgPath) and not force:
    displayError("clue.deploy.yaml already exists. Use --force to overwrite.", quitProcess = true)
    return
  writeFile(cfgPath, buildDeployYaml(project, deployType, version, host, user, remoteDir))
  displaySuccess("Created " & cfgPath)
