# Clue - A cool toolkit for Nim developers
#
# (c) 2026 George Lemon | LGPLv3 License
#          Made by Humans from OpenPeeps
#          https://github.com/openpeeps/clue

## Static code analysis via nimalyzer.

import std/[os, osproc, strutils]

import pkg/kapsis/[runtime, interactive/prompts]

import ../pkgmanager/configs

const defaultConfig = """# Generated by `clue doctor check`
# Nimalyzer config — edit rules as needed

# Source directories
directory src
directory tests

# Cyclomatic complexity (40 = high risk threshold)
check complexity all 40

# Unused parameters
check params used procedures
check params used macros

# Variable hiding
check localHides

# var → let/const upgrades
check varUplevel

# if/when best practices
check ifStatements all

# Empty for loops
check forStatements empty

# Empty except branches
check tryStatements empty

# Full variable declarations (type + value)
check varDeclared full

# Documentation on public declarations
check hasDoc all
"""

proc findNimalyzer(): string =
  ## Return the path to the nimalyzer binary, or "" if not found.
  result = findExe("nimalyzer")
  if result.len > 0: return
  # Fallback: check ~/.nimble/bin
  let nimbleBin = getHomeDir() / ".nimble" / "bin" / "nimalyzer"
  if fileExists(nimbleBin):
    result = nimbleBin

proc doctorCommand*(v: Values) =
  ## Run static code analysis on the current project using nimalyzer.
  let nimalyzerPath = findNimalyzer()
  if nimalyzerPath.len == 0:
    displayError("nimalyzer not found. Install it: nimble install nimalyzer",
      quitProcess = true)

  let cfgPath = getCurrentDir() / ".nimalyzer.cfg"
  if not fileExists(cfgPath):
    displayInfo("Generating default .nimalyzer.cfg")
    writeFile(cfgPath, defaultConfig)

  displayInfo("Running nimalyzer...")
  let exitCode = execCmd(nimalyzerPath & " " & cfgPath)
  if exitCode != 0:
    displayWarning("nimalyzer found issues (exit " & $exitCode & ")")
  else:
    displaySuccess("No issues found")
