// Auto-generated by Clue. Do not edit.

package mathlib

/*
#include "../../c/mathlib.h"
*/
import "C"
import "unsafe"

type Vector struct {
	X float64
	Y float64
	Z float64
}

const (
	OpAdd = C.MathOp_opAdd
	OpSub = C.MathOp_opSub
	OpMul = C.MathOp_opMul
	OpDiv = C.MathOp_opDiv
)

// Add two vectors, store result in `res`
func Vec_add(a *Vector, b *Vector, res *Vector) {
	C.vec_add((*C.Vector)(unsafe.Pointer(a)), (*C.Vector)(unsafe.Pointer(b)), (*C.Vector)(unsafe.Pointer(res)))
}

// Compute the length (magnitude) of a vector
func Vec_length(v *Vector) float64 {
	return float64(C.vec_length((*C.Vector)(unsafe.Pointer(v))))
}

// Scale a vector in-place by a factor
func Vec_scale(v *Vector, factor float64) {
	C.vec_scale((*C.Vector)(unsafe.Pointer(v)), C.double(factor))
}

// Compute the dot product of two vectors
func Vec_dot(a *Vector, b *Vector) float64 {
	return float64(C.vec_dot((*C.Vector)(unsafe.Pointer(a)), (*C.Vector)(unsafe.Pointer(b))))
}
