/* Auto-generated by Clue. Do not edit. */

#ifndef MATHLIB_H
#define MATHLIB_H

#ifndef MATHLIB_API
#  define MATHLIB_API extern
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
  double x;
  double y;
  double z;
} Vector;

typedef enum {
  MathOp_opAdd,
  MathOp_opSub,
  MathOp_opMul,
  MathOp_opDiv
} MathOp;

/**
 * Add two vectors, store result in `res`
 */
MATHLIB_API void vec_add(Vector* a, Vector* b, Vector* res);

/**
 * Compute the length (magnitude) of a vector
 */
MATHLIB_API double vec_length(Vector* v);

/**
 * Scale a vector in-place by a factor
 */
MATHLIB_API void vec_scale(Vector* v, double factor);

/**
 * Compute the dot product of two vectors
 */
MATHLIB_API double vec_dot(Vector* a, Vector* b);

#ifdef __cplusplus
}
#endif

#endif /* MATHLIB_H */
