# Auto-generated by Clue. Do not edit.

@[Link(ldflags: "-L #{__DIR__}/../../../../build -lmathlib")]
lib LibMathlib
  @[Extern]
  struct Vector
    x : Float64
    y : Float64
    z : Float64
  end

  enum MathOp
    OpAdd
    OpSub
    OpMul
    OpDiv
  end

  # Add two vectors, store result in `res`
  fun vec_add(a : Vector*, b : Vector*, res : Vector*) : Void

  # Compute the length (magnitude) of a vector
  fun vec_length(v : Vector*) : Float64

  # Scale a vector in-place by a factor
  fun vec_scale(v : Vector*, factor : Float64) : Void

  # Compute the dot product of two vectors
  fun vec_dot(a : Vector*, b : Vector*) : Float64
end
