name: release
on:
  push:
    tags: ['*.*.*']
  workflow_dispatch:
jobs:
  release:
    permissions:
      contents: write
    uses: nimbase/setup-nim-action/.github/workflows/release_clue.yml@main
    with:
      os: '[{"os":"ubuntu-latest"},{"os":"windows-latest"},{"os":"macos-14"},{"os":"macos-15-intel"}]'
      nim-version: '2.2.10'
      app-name: clue